const axios = require('axios');

module.exports = [
    {
        name: 'kira', 
        category: 'ai',
        description: 'Talk with Kira AI',
        usage: '.kira <question>',
        async execute(sock, msg, args) {
            if (!args[0]) return await sock.sendMessage(msg.key.remoteJid, { text: '⚠️ Ask something!' });
            // 'q' മാറ്റി 'prompt' ആക്കി
            const res = await axios.get(`https://eliteprotech-apis.zone.id/talk-ai?prompt=${encodeURIComponent(args.join(' '))}`);
            await sock.sendMessage(msg.key.remoteJid, { text: res.data.result || res.data.message });
        }
    },
    {
        name: 'chatgpt',
        category: 'ai',
        description: 'ChatGPT',
        usage: '.chatgpt <query>',
        async execute(sock, msg, args) {
            // 'q' മാറ്റി 'prompt' ആക്കി
            const res = await axios.get(`https://eliteprotech-apis.zone.id/chatgpt?prompt=${encodeURIComponent(args.join(' '))}`);
            await sock.sendMessage(msg.key.remoteJid, { text: res.data.result });
        }
    },
    {
        name: 'copilot',
        category: 'ai',
        description: 'Microsoft Copilot',
        usage: '.copilot <query>',
        async execute(sock, msg, args) {
            // 'q' മാറ്റി 'prompt' ആക്കി
            const res = await axios.get(`https://eliteprotech-apis.zone.id/copilot?prompt=${encodeURIComponent(args.join(' '))}`);
            await sock.sendMessage(msg.key.remoteJid, { text: res.data.result });
        }
    },
    {
        name: 'flux',
        category: 'ai',
        description: 'Generate AI images',
        usage: '.flux <prompt>',
        async execute(sock, msg, args) {
            await sock.sendMessage(msg.key.remoteJid, { text: '⏳ Generating...' });
            // 'q' മാറ്റി 'prompt' ആക്കി
            const url = `https://eliteprotech-apis.zone.id/flux?prompt=${encodeURIComponent(args.join(' '))}`;
            await sock.sendMessage(msg.key.remoteJid, { image: { url: url }, caption: '✨ Generated by Flux AI' });
        }
    }
];