const axios = require("axios");

module.exports = {
    name: "blackpink",
    alias: ["blackpinklogo"],
    category: "logo",
    description: "Generate Blackpink Logo",

    async execute(sock, msg, args) {

        const jid = msg.key.remoteJid;
        const text = args.join(" ").trim();

        if (!text) {
            return await sock.sendMessage(
                jid,
                {
                    text:
`❌ Give some text.

Example:
.blackpink KIRA-X`
                },
                { quoted: msg }
            );
        }

        try {

            await sock.sendMessage(jid, {
                react: {
                    text: "🎨",
                    key: msg.key
                }
            });

            const { data } = await axios.get(
                `https://jerrycoder.oggyapi.workers.dev/ephoto/blackpinklogo?text=${encodeURIComponent(text)}`
            );

            console.log("BLACKPINK API:", data);

            const imageUrl =
                data.result ||
                data.url ||
                data.image;

            if (!imageUrl) {
                throw new Error(
                    "No image URL returned"
                );
            }

            await sock.sendMessage(
                jid,
                {
                    image: {
                        url: imageUrl
                    },
                    caption:
`🖤💗 *BLACKPINK LOGO*

📝 Text: ${text}
🩸 Generated by KIRA-X-MD`
                },
                { quoted: msg }
            );

            await sock.sendMessage(jid, {
                react: {
                    text: "✅",
                    key: msg.key
                }
            });

        } catch (err) {

            console.log(
                "BLACKPINK ERROR:",
                err
            );

            await sock.sendMessage(jid, {
                react: {
                    text: "❌",
                    key: msg.key
                }
            });

            await sock.sendMessage(
                jid,
                {
                    text:
"❌ Failed to generate logo."
                },
                { quoted: msg }
            );
        }
    }
};