module.exports = {
    name: "luxurygold",
    alias: ["gold"],
    category: "logo",
    description: "Luxury Gold Text Logo",

    async execute(sock, msg, args) {
        const jid = msg.key.remoteJid;
        const text = args.join(" ").trim();

        if (!text) {
            return sock.sendMessage(
                jid,
                {
                    text: "❌ Example:\n.luxurygold KIRA X MD"
                },
                { quoted: msg }
            );
        }

        const url =
            `https://jerrycoder.oggyapi.workers.dev/ephoto/luxurygold?text=${encodeURIComponent(text)}`;

        await sock.sendMessage(
            jid,
            {
                image: { url },
                caption:
`${text}

> *Generated by KIRA X MD*`
            },
            { quoted: msg }
        );
    }
};