const axios = require("axios");

module.exports = {
    name: "pixelglitch",
    alias: ["pglitch"],
    category: "logo",
    description: "Generate Pixel Glitch Logo",

    async execute(sock, msg, args) {
        const jid = msg.key.remoteJid;
        const text = args.join(" ").trim();

        if (!text) {
            return sock.sendMessage(
                jid,
                {
                    text:
                        "❌ Example:\n.pixelglitch JerryCoder"
                },
                { quoted: msg }
            );
        }

        try {
            await sock.sendMessage(jid, {
                react: {
                    text: "🎨",
                    key: msg.key
                }
            });

            const image =
                `https://jerrycoder.oggyapi.workers.dev/ephoto/pixelglitch?text=${encodeURIComponent(text)}`;

            await sock.sendMessage(
                jid,
                {
                    image: {
                        url: image
                    },
                    caption:
                        `✨ *Pixel Glitch Logo*\n📝 Text: ${text}\n\n> *Generated by KIRA X MD*`
                },
                { quoted: msg }
            );

            await sock.sendMessage(jid, {
                react: {
                    text: "✅",
                    key: msg.key
                }
            });

        } catch (e) {
            console.log("PIXELGLITCH ERROR:", e);

            await sock.sendMessage(
                jid,
                {
                    text:
                        "❌ Failed to generate logo."
                },
                { quoted: msg }
            );
        }
    }
};