const axios = require("axios");

module.exports = {
    name: "soravid",
    alias: ["aivideo", "genvideo"],
    category: "ai",
    description: "AI Video Generator",

    async execute(sock, msg, args) {
        const jid = msg.key.remoteJid;
        const prompt = args.join(" ").trim();

        if (!prompt) {
            return sock.sendMessage(
                jid,
                {
                    text:
                        "❌ Example:\n.soravid a man gaming on gaming room night vibe"
                },
                { quoted: msg }
            );
        }

        try {
            await sock.sendMessage(jid, {
                react: {
                    text: "🎬",
                    key: msg.key
                }
            });

            await sock.sendMessage(
                jid,
                {
                    text:
`⏳ Generating AI video...

📝 Prompt: ${prompt}

Please wait...`
                },
                { quoted: msg }
            );

            const api =
                `https://jerrycoder.oggyapi.workers.dev/ai/soravid?prompt=${encodeURIComponent(prompt)}`;

            const { data } = await axios.get(api, {
                timeout: 120000
            });

            console.log("SORAVID RESPONSE:", data);

            const video =
                data?.result?.url ||
                data?.result?.video ||
                data?.data?.url ||
                data?.data?.video ||
                data?.url ||
                data?.video;

            if (!video)
                throw new Error("No video returned");

            await sock.sendMessage(
                jid,
                {
                    video: {
                        url: video
                    },
                    caption:
`🎬 *AI Generated Video*

📝 Prompt: ${prompt}

> *Generated by KIRA X MD*`
                },
                { quoted: msg }
            );

            await sock.sendMessage(jid, {
                react: {
                    text: "✅",
                    key: msg.key
                }
            });

        } catch (e) {
            console.log("SORAVID ERROR:", e);

            await sock.sendMessage(
                jid,
                {
                    text:
                        "❌ Video generation failed."
                },
                { quoted: msg }
            );

            await sock.sendMessage(jid, {
                react: {
                    text: "❌",
                    key: msg.key
                }
            });
        }
    }
};