const axios = require("axios");

module.exports = {
    name: "soraimg",
    alias: ["txt2img", "text2img"],
    category: "ai",
    description: "Text To Image Generator",

    async execute(sock, msg, args) {
        const jid = msg.key.remoteJid;
        const prompt = args.join(" ").trim();

        if (!prompt) {
            return sock.sendMessage(
                jid,
                {
                    text:
                        "❌ Example:\n.soraimg Anime witch girl"
                },
                { quoted: msg }
            );
        }

        try {
            await sock.sendMessage(jid, {
                react: {
                    text: "🎨",
                    key: msg.key
                }
            });

            await sock.sendMessage(
                jid,
                {
                    text:
`⏳ Generating image...

📝 Prompt: ${prompt}

Please wait...`
                },
                { quoted: msg }
            );

            const api =
                `https://jerrycoder.oggyapi.workers.dev/ai/soraimg?prompt=${encodeURIComponent(prompt)}`;

            const { data } = await axios.get(api, {
                timeout: 60000
            });

            console.log("SORAIMG RESPONSE:", data);

            const image =
                data?.result?.url ||
                data?.result?.image ||
                data?.data?.url ||
                data?.data?.image ||
                data?.url ||
                data?.image;

            if (!image)
                throw new Error("No image returned");

            await sock.sendMessage(
                jid,
                {
                    image: {
                        url: image
                    },
                    caption:
`🎨 *AI Generated Image*

📝 Prompt: ${prompt}

> *Generated by KIRA X MD*`
                },
                { quoted: msg }
            );

            await sock.sendMessage(jid, {
                react: {
                    text: "✅",
                    key: msg.key
                }
            });

        } catch (e) {
            console.log("SORAIMG ERROR:", e);

            await sock.sendMessage(
                jid,
                {
                    text:
                        "❌ Image generation failed."
                },
                { quoted: msg }
            );

            await sock.sendMessage(jid, {
                react: {
                    text: "❌",
                    key: msg.key
                }
            });
        }
    }
};